# Make ML models for prediction gte parameters

# Parameters

In [3]:
from config import parameters as gtep

In [6]:
for alias, parameter in gtep.items():
    print(f"{alias:<15}: {parameter}")

l              : thermal_conductivity
hc             : heat_capacity
Cp             : heat_capacity_pressure
Cv             : heat_capacity_volume
k              : adiabatic_index
gc             : gas_const
eo             : excess_oxidizing
T              : static_temperature
P              : static_pressure
D              : staticdensity
TT             : total_temperature
PP             : total_pressure
DD             : total_density
m              : mass
v              : volume
a              : sound_speed
a_critical     : critical_sound_speed
c              : absolute_velocity
u              : portable_velocity
w              : relative_velocity
mf             : mass_flow
pipi           : total_pressure_ratio
pi             : static_pressure_ratio
titi           : total_temperature_ratio
ti             : static_temperature_ratio
mach           : mach_number
Nu             : nusselt_number
efficiency     : efficiency
effeff         : total_efficiency
peff           : pressure_efficiency
effburn        : efficiency_burn
power          : power

# Generate data

In [31]:
import time
import numpy as np
import pandas as pd

from thermodynamics import gas_const, heat_capacity_p
from substance import Substance

## Compressor

In [29]:
from gte import Compressor

In [30]:
air = Substance(
    "air",
    composition={"N2": 0.78, "O2": 0.21, "Ar": 0.009, "CO2": 0.0004},
    parameters={
        gtep.mf: 50.0,
        gtep.gc: 287.14,
        gtep.TT: 300.0,
        gtep.PP: 101325.0,
        gtep.Cp: 1006.0,
        gtep.k: 1.4,
        gtep.c: 0.0,
    },
    functions={
        gtep.gc: lambda temperature: gas_const("air"),
        gtep.Cp: lambda temperature: heat_capacity_p("air", temperature),
    },
)

In [20]:
data = []

In [21]:
for pipi in range(4, 12, 1):
    for effeff in range(85, 95, 1):
        compressor = Compressor("generator")
        setattr(compressor, gtep.pipi, pipi)
        setattr(compressor, gtep.effeff, effeff / 100)

        compressor.calculate(air)

        data.append(compressor.summary)

--------------------
total_pressure_ratio: 4
total_efficiency: 0.85
power: 8606001.717811026
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 470.0249781484548
total_pressure_outlet: 405300.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1025.0383159977407
total_density_outlet: 3.00304589708258
adiabatic_index_outlet: 1.3891322066669132
critical_sound_speed_outlet: 396.1630928926236
--------------------
--------------------
total_pressure_ratio: 4
total_efficiency: 0.86
power: 8506187.700602202
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 468.0771215803783
total_pressure_outlet: 405300.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1024.6820445828537
total_density_outlet: 3.0155427750652457
adiabatic_index_outlet: 1.389320177892236
critical_sound_speed_outlet: 395.3525545690573
--------------------
--------------------
total_pressure_ratio: 4
total_efficiency: 0.87
power: 8408661.350665519
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 466.17325577122546
total_pressure_outlet: 405300.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1024.3355517539167
total_density_outlet: 3.0278583438251623
adiabatic_index_outlet: 1.3895031641425994
critical_sound_speed_outlet: 394.5585766259597
--------------------
--------------------
total_pressure_ratio: 4
total_efficiency: 0.88
power: 8313344.937051545
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 464.3119103962997
total_pressure_outlet: 405300.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1023.9984717522639
total_density_outlet: 3.0399964992289275
adiabatic_index_outlet: 1.3896813445289913
critical_sound_speed_outlet: 393.78065324540745
--------------------
--------------------
total_pressure_ratio: 4
total_efficiency: 0.89
power: 8220164.21023591
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 462.49167983538416
total_pressure_outlet: 405300.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1023.6704558998832
total_density_outlet: 3.0519610269690634
adiabatic_index_outlet: 1.3898548901812569
critical_sound_speed_outlet: 393.0182991371029
--------------------
--------------------
total_pressure_ratio: 4
total_efficiency: 0.9
power: 8129048.209386142
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 460.7112196553163
total_pressure_outlet: 405300.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1023.35117165171
total_density_outlet: 3.063755606410178
adiabatic_index_outlet: 1.390023964667357
critical_sound_speed_outlet: 392.27104850068343
--------------------
--------------------
total_pressure_ratio: 4
total_efficiency: 0.91
power: 8039929.08229211
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 458.9692433194683
total_pressure_outlet: 405300.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1023.0403017083876
total_density_outlet: 3.075383814275674
adiabatic_index_outlet: 1.390188724387538
critical_sound_speed_outlet: 391.5384540507613
--------------------
--------------------
total_pressure_ratio: 4
total_efficiency: 0.92
power: 7952741.916999674
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 457.26451910723426
total_pressure_outlet: 405300.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1022.7375431851648
total_density_outlet: 3.0868491281826973
adiabatic_index_outlet: 1.3903493189450757
critical_sound_speed_outlet: 390.8200861002812
--------------------
--------------------
total_pressure_ratio: 4
total_efficiency: 0.93
power: 7867424.584269707
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 455.5958672280522
total_pressure_outlet: 405300.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1022.4426068329363
total_density_outlet: 3.098154930032553
adiabatic_index_outlet: 1.3905058914951451
critical_sound_speed_outlet: 390.1155316981436
--------------------
--------------------
total_pressure_ratio: 4
total_efficiency: 0.94
power: 7783917.590058887
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 453.9621571157768
total_pressure_outlet: 405300.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1022.1552163077511
total_density_outlet: 3.1093045092634477
adiabatic_index_outlet: 1.390658579073245
critical_sound_speed_outlet: 389.4243938173567
--------------------
--------------------
total_pressure_ratio: 5
total_efficiency: 0.85
power: 10329038.634841118
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 503.5407637558566
total_pressure_outlet: 506625.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1031.4292171567522
total_density_outlet: 3.5039531150039624
adiabatic_index_outlet: 1.3857908906659955
critical_sound_speed_outlet: 409.8376249437831
--------------------
--------------------
total_pressure_ratio: 5
total_efficiency: 0.86
power: 10209395.645817164
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 501.22030327065403
total_pressure_outlet: 506625.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1030.971925197838
total_density_outlet: 3.52017509302902
adiabatic_index_outlet: 1.3860280666544784
critical_sound_speed_outlet: 408.9068742901664
--------------------
--------------------
total_pressure_ratio: 5
total_efficiency: 0.87
power: 10092490.771126844
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 498.95195575806974
total_pressure_outlet: 506625.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1030.5269038698616
total_density_outlet: 3.5361785986250682
adiabatic_index_outlet: 1.3862591585959216
critical_sound_speed_outlet: 407.9947930970115
--------------------
--------------------
total_pressure_ratio: 5
total_efficiency: 0.88
power: 9978231.114764297
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 496.73398950904266
total_pressure_outlet: 506625.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1030.0937080621813
total_density_outlet: 3.551967984791362
adiabatic_index_outlet: 1.3864843756536818
critical_sound_speed_outlet: 407.1008199615059
--------------------
--------------------
total_pressure_ratio: 5
total_efficiency: 0.89
power: 9866527.935310664
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 494.56474859569266
total_pressure_outlet: 506625.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1029.6719126971554
total_density_outlet: 3.5675474904018962
adiabatic_index_outlet: 1.386703918161577
critical_sound_speed_outlet: 406.2244159766488
--------------------
--------------------
total_pressure_ratio: 5
total_efficiency: 0.9
power: 9757296.41624078
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 492.44264877264004
total_pressure_outlet: 506625.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1029.2611116655294
total_density_outlet: 3.58292124390798
adiabatic_index_outlet: 1.3869179780582939
critical_sound_speed_outlet: 405.3650636050496
--------------------
--------------------
total_pressure_ratio: 5
total_efficiency: 0.91
power: 9650455.45130422
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 490.3661736415823
total_pressure_outlet: 506625.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1028.8609168264215
total_density_outlet: 3.5980932668969707
adiabatic_index_outlet: 1.387126739297817
critical_sound_speed_outlet: 404.5222656203525
--------------------
--------------------
total_pressure_ratio: 5
total_efficiency: 0.92
power: 9545927.443839006
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 488.3338710595976
total_pressure_outlet: 506625.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1028.470957067548
total_density_outlet: 3.613067477513715
adiabatic_index_outlet: 1.3873303782373094
critical_sound_speed_outlet: 403.69554411155116
--------------------
--------------------
total_pressure_ratio: 5
total_efficiency: 0.93
power: 9443638.118973387
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 486.3443497732699
total_pressure_outlet: 506625.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1028.0908774216439
total_density_outlet: 3.6278476937510433
adiabatic_index_outlet: 1.3875290640037945
critical_sound_speed_outlet: 402.88443954583613
--------------------
--------------------
total_pressure_ratio: 5
total_efficiency: 0.94
power: 9343516.347760484
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 484.39627626223887
total_pressure_outlet: 506625.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1027.7203382353318
total_density_outlet: 3.6424376366151483
adiabatic_index_outlet: 1.3877229588409035
critical_sound_speed_outlet: 402.08850988596623
--------------------
--------------------
total_pressure_ratio: 6
total_efficiency: 0.85
power: 11816242.700103626
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 532.2979315327493
total_pressure_outlet: 607950.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1037.2558324484967
total_density_outlet: 3.9775842583793817
adiabatic_index_outlet: 1.3827942133453304
critical_sound_speed_outlet: 421.18679181026033
--------------------
--------------------
total_pressure_ratio: 6
total_efficiency: 0.86
power: 11679554.338750418
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 529.6616610531031
total_pressure_outlet: 607950.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1036.710192412041
total_density_outlet: 3.997381779573992
adiabatic_index_outlet: 1.3830728634979634
critical_sound_speed_outlet: 420.1602709470991
--------------------
--------------------
total_pressure_ratio: 6
total_efficiency: 0.87
power: 11545989.647029696
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 527.084297558467
total_pressure_outlet: 607950.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1036.1788617993182
total_density_outlet: 4.01692837946422
adiabatic_index_outlet: 1.3833445961805522
critical_sound_speed_outlet: 419.15403788411663
--------------------
--------------------
total_pressure_ratio: 6
total_efficiency: 0.88
power: 11415442.799982907
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 524.5638933542403
total_pressure_outlet: 607950.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1035.6613367644325
total_density_outlet: 4.036228760798019
adiabatic_index_outlet: 1.383609639293911
critical_sound_speed_outlet: 418.16748983540447
--------------------
--------------------
total_pressure_ratio: 6
total_efficiency: 0.89
power: 11287812.699258635
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 522.0985855920727
total_pressure_outlet: 607950.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1035.157135339346
total_density_outlet: 4.055287510176923
adiabatic_index_outlet: 1.3838682116148795
critical_sound_speed_outlet: 417.20004795130643
--------------------
--------------------
total_pressure_ratio: 6
total_efficiency: 0.9
power: 11163002.712087575
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 519.6865916982348
total_pressure_outlet: 607950.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1034.665796319874
total_density_outlet: 4.074109101629456
adiabatic_index_outlet: 1.3841205232162046
critical_sound_speed_outlet: 416.251156127333
--------------------
--------------------
total_pressure_ratio: 6
total_efficiency: 0.91
power: 11040920.42737283
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 517.326205094795
total_pressure_outlet: 607950.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1034.1868782158672
total_density_outlet: 4.092697900050514
adiabatic_index_outlet: 1.3843667758652058
critical_sound_speed_outlet: 415.3202798843731
--------------------
--------------------
total_pressure_ratio: 6
total_efficiency: 0.92
power: 10921477.427599717
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 515.0157911919104
total_pressure_outlet: 607950.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1033.7199582615258
total_density_outlet: 4.111058164512891
adiabatic_index_outlet: 1.3846071634023362
critical_sound_speed_outlet: 414.4069053152136
--------------------
--------------------
total_pressure_ratio: 6
total_efficiency: 0.93
power: 10804589.075380417
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 512.7537836313644
total_pressure_outlet: 607950.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1033.2646314820508
total_density_outlet: 4.1291940514567465
adiabatic_index_outlet: 1.3848418721007036
critical_sound_speed_outlet: 413.5105380927772
--------------------
--------------------
total_pressure_ratio: 6
total_efficiency: 0.94
power: 10690174.313548934
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 510.5386807631302
total_pressure_outlet: 607950.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1032.8205098130989
total_density_outlet: 4.147109617762527
adiabatic_index_outlet: 1.3850710810075622
critical_sound_speed_outlet: 412.6307025358511
--------------------
--------------------
total_pressure_ratio: 7
total_efficiency: 0.85
power: 13131492.188984927
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 557.5933754886901
total_pressure_outlet: 709275.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1042.5944297872707
total_density_outlet: 4.4299961716841345
adiabatic_index_outlet: 1.3800891075334036
critical_sound_speed_outlet: 430.90110151742465
--------------------
--------------------
total_pressure_ratio: 7
total_efficiency: 0.86
power: 12979789.344422594
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0
total_pressure_inlet: 101325.0
heat_capacity_pressure_inlet: 1006.0
adiabatic_index_inlet: 1.4
absolute_velocity_inlet: 0.0
mass_flow_outlet: 50.0
total_temperature_outlet: 554.6824021767839
total_pressure_outlet: 709275.0
gas_const_outlet: 287.14
heat_capacity_pressure_outlet: 1041.971171875195
total_density_outlet: 4.453244792114514
adiabatic_index_outlet: 1.380402943994311
critical_sound_speed_outlet: 429.79537599160767
--------------------
--------------------
total_pressure_ratio: 7
total_efficiency: 0.87
power: 12831548.434261981
mass_flow_inlet: 50.0
gas_const_inlet: 287.14
total_temperature_inlet: 300.0

In [77]:
df = pd.DataFrame(data)
df

,total_pressure_ratio,total_efficiency,power,mass_flow_inlet,gas_const_inlet,total_temperature_inlet,total_pressure_inlet,heat_capacity_pressure_inlet,adiabatic_index_inlet,absolute_velocity_inlet,mass_flow_outlet,total_temperature_outlet,total_pressure_outlet,gas_const_outlet,heat_capacity_pressure_outlet,total_density_outlet,adiabatic_index_outlet,critical_sound_speed_outlet
0,4,0.85,8.606002e+06,50.0,287.14,300.0,101325.0,1006.0,1.4,0.0,50.0,470.024978,405300.0,287.14,1025.038316,3.003046,1.389132,396.163093
1,4,0.86,8.506188e+06,50.0,287.14,300.0,101325.0,1006.0,1.4,0.0,50.0,468.077122,405300.0,287.14,1024.682045,3.015543,1.389320,395.352555
2,4,0.87,8.408661e+06,50.0,287.14,300.0,101325.0,1006.0,1.4,0.0,50.0,466.173256,405300.0,287.14,1024.335552,3.027858,1.389503,394.558577
3,4,0.88,8.313345e+06,50.0,287.14,300.0,101325.0,1006.0,1.4,0.0,50.0,464.311910,405300.0,287.14,1023.998472,3.039996,1.389681,393.780653
4,4,0.89,8.220164e+06,50.0,287.14,300.0,101325.0,1006.0,1.4,0.0,50.0,462.491680,405300.0,287.14,1023.670456,3.051961,1.389855,393.018299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,11,0.90,1.635790e+07,50.0,287.14,300.0,101325.0,1006.0,1.4,0.0,50.0,619.088201,1114575.0,287.14,1056.181427,6.269936,1.373374,453.575328
76,11,0.91,1.618006e+07,50.0,287.14,300.0,101325.0,1006.0,1.4,0.0,50.0,615.719384,1114575.0,287.14,1055.420228,6.304241,1.373744,452.365226
77,11,0.92,1.600605e+07,50.0,287.14,300.0,101325.0,1006.0,1.4,0.0,50.0,612.420605,1114575.0,287.14,1054.676373,6.338198,1.374106,451.176854
78,11,0.93,1.583573e+07,50.0,287.14,300.0,101325.0,1006.0,1.4,0.0,50.0,609.189705,1114575.0,287.14,1053.949342,6.371813,1.374461,450.009619
79,11,0.94,1.566899e+07,50.0,287.14,300.0,101325.0,1006.0,1.4,0.0,50.0,606.024612,1114575.0,287.14,1053.238636,6.405092,1.374808,448.862950

In [81]:
now = time.strftime("%Y-%m-%d-%H-%M-%S", time.localtime())
df.to_excel(f"data/compressor_{now}.xlsx", index=False, header=True)

# ML

In [118]:
import os
import pickle

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error

In [98]:
MODELS = (LinearRegression, DecisionTreeRegressor, RandomForestRegressor)
METRICS = (mean_absolute_error, mean_squared_error)

In [99]:
os.listdir("data")

['compressor_2025-11-02-18-04-09.xlsx']

In [84]:
df = pd.read_excel("data/compressor_2025-11-02-18-04-09.xlsx")
df

,total_pressure_ratio,total_efficiency,power,mass_flow_inlet,gas_const_inlet,total_temperature_inlet,total_pressure_inlet,heat_capacity_pressure_inlet,adiabatic_index_inlet,absolute_velocity_inlet,mass_flow_outlet,total_temperature_outlet,total_pressure_outlet,gas_const_outlet,heat_capacity_pressure_outlet,total_density_outlet,adiabatic_index_outlet,critical_sound_speed_outlet
0,4,0.85,8.606002e+06,50,287.14,300,101325,1006,1.4,0,50,470.024978,405300,287.14,1025.038316,3.003046,1.389132,396.163093
1,4,0.86,8.506188e+06,50,287.14,300,101325,1006,1.4,0,50,468.077122,405300,287.14,1024.682045,3.015543,1.389320,395.352555
2,4,0.87,8.408661e+06,50,287.14,300,101325,1006,1.4,0,50,466.173256,405300,287.14,1024.335552,3.027858,1.389503,394.558577
3,4,0.88,8.313345e+06,50,287.14,300,101325,1006,1.4,0,50,464.311910,405300,287.14,1023.998472,3.039996,1.389681,393.780653
4,4,0.89,8.220164e+06,50,287.14,300,101325,1006,1.4,0,50,462.491680,405300,287.14,1023.670456,3.051961,1.389855,393.018299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,11,0.90,1.635790e+07,50,287.14,300,101325,1006,1.4,0,50,619.088201,1114575,287.14,1056.181427,6.269936,1.373374,453.575328
76,11,0.91,1.618006e+07,50,287.14,300,101325,1006,1.4,0,50,615.719384,1114575,287.14,1055.420228,6.304241,1.373744,452.365226
77,11,0.92,1.600605e+07,50,287.14,300,101325,1006,1.4,0,50,612.420605,1114575,287.14,1054.676373,6.338198,1.374106,451.176854
78,11,0.93,1.583573e+07,50,287.14,300,101325,1006,1.4,0,50,609.189705,1114575,287.14,1053.949342,6.371813,1.374461,450.009619
79,11,0.94,1.566899e+07,50,287.14,300,101325,1006,1.4,0,50,606.024612,1114575,287.14,1053.238636,6.405092,1.374808,448.862950

In [119]:
targets = (gtep.pipi, gtep.effeff, gtep.power)

In [125]:
for target in targets:
    print(target)

    y = df[target]
    x = df.drop([target], axis=1)

    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, shuffle=True)

    for Model in MODELS:
        print(f"\t{Model.__name__}")
        model = Model()
        model.fit(x_train, y_train)
        for metric in METRICS:
            print(f"\t\t{metric.__name__:<20}: {metric(y_test, model.predict(x_test)):.6f}")

        with open(f"models/compressor_{target}.pkl", "wb") as file:
            pickle.dump(model, file)

        print()

total_pressure_ratio
	LinearRegression
		mean_absolute_error : 0.000000
		mean_squared_error  : 0.000000

	DecisionTreeRegressor
		mean_absolute_error : 0.037037
		mean_squared_error  : 0.037037

	RandomForestRegressor
		mean_absolute_error : 0.138889
		mean_squared_error  : 0.066322

total_efficiency
	LinearRegression
		mean_absolute_error : 0.001602
		mean_squared_error  : 0.000005

	DecisionTreeRegressor
		mean_absolute_error : 0.011481
		mean_squared_error  : 0.000152

	RandomForestRegressor
		mean_absolute_error : 0.009307
		mean_squared_error  : 0.000159

power
	LinearRegression
		mean_absolute_error : 1.362309
		mean_squared_error  : 3.302799

	DecisionTreeRegressor
		mean_absolute_error : 143061.633921
		mean_squared_error  : 27067448643.289940

	RandomForestRegressor
		mean_absolute_error : 130114.758525
		mean_squared_error  : 32825159278.360275